Title: Daniel Godoi Alves Watrin
logo: docs/assets/e2d2ce1d-77c8-41c2-86e7-f62044d1d49d.jpg
Description: Estudante de ciência da computação
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
